### ISSUE TITLE
HTML 

### ISSUE THREAD

**Issue by a1exlin** [a1exlin/Module-6-Challenge#3]
Nav bar
Search button
box for the weather to display
clean coce

**Comment by yabhinavy** [comment]
Hi @a1exlin, I am interested in working at your issue. It will be so nice of you if you could add me to Assignees to look into this issue, I will be giving my best. For that I would also be needing some more insights about this project, allow me that as well. Thank you.

**Comment by a1exlin** [comment]
@yabhinavy Hi there! I apologize for the late response. I've resolved these issues already, however I will still have more to cover!

**Comment by yabhinavy** [comment]
Feel free to ping me if you have some issue open.
